---
- hosts: all
  become: yes
  gather_facts: no
  tasks:
    - apt: autoclean=yes
    - apt: update_cache=yes
    - apt: name={{ item }} state=present
      with_items:
        - curl
        - gpg
        - ca-certificates
