---
- hosts: all
  become: yes
  gather_facts: no
  tasks:
    #- get_url: url=https://packages.fluentbit.io/fluentbit.key dest=/etc/apt/keyrings/fluentbit-keyring.asc checksum=sha256:df248e2d7103ca62cb683c20a077198d0fb0a7f79dbf53a604af0317de3b4711
    #- setup: gather_subset='distribution_release'
    #- lineinfile: path=/etc/apt/sources.list.d/fluentbit.list line='deb [signed-by=/etc/apt/keyrings/fluentbit-keyring.asc] https://packages.fluentbit.io/ubuntu/{{ ansible_facts.distribution_release }} {{ ansible_facts.distribution_release }} main' state=present create=yes mode=644
    #- apt: autoclean=yes
    #- apt: update_cache=yes
    #- apt: name=fluent-bit state=present
    - copy: src=../files/newrelic-infra/logging.d/logging.yml dest=/etc/newrelic-infra/logging.d/logging.yml owner=root mode=644
