#cloud-config

timezone: Asia/Tokyo
package_update: true
packages:
  - ansible
  - curl
  - git
  - unzip

runcmd:
  - |
    set -e

    echo "private-isuのセットアップ(nodejs,php8,composerをスキップ)"
    GITDIR="/tmp/private-isu"
    rm -rf ${GITDIR}
    git clone -b add-tag-php8-to-php-app --single-branch --depth=1 https://github.com/sunakan/private-isu.git ${GITDIR}
    cd ${GITDIR}/provisioning/
    sed -i 's/isu-app/localhost ansible_connection=local/' hosts
    ansible-playbook -i hosts image/ansible/playbooks.yml --skip-tags "nodejs,php8,composer"

    echo "自作のセットアップ(for app)"
    GITDIR="/tmp/isucon-suburi"
    rm -rf ${GITDIR}
    sudo -u isucon git clone --depth=1 https://github.com/sunakan/isucon-suburi.git ${GITDIR}
    cd ${GITDIR}/ansible/
    ansible-playbook -i hosts playbooks/playbooks-app.yaml
