logs:
  - name: alternatives.log
    file: /var/log/alternatives.log
    attributes:
      logtype: linux_alternatives
  - name: cloud-init.log
    file: /var/log/cloud-init.log
    attributes:
      logtype: linux_cloud-init
  - name: auth.log
    file: /var/log/auth.log
    attributes:
      logtype: linux_auth
  - name: dpkg.log
    file: /var/log/dpkg.log
    attributes:
      logtype: linux_dpkg
  - name: syslog
    file: /var/log/syslog
    attributes:
      logtype: linux_syslog
